# Benoit Saint-Moulin
# Traktor Bridge : compiles the core to native extension modules (Nuitka)

"""python compile_core.py

Copies the package and main.py to build/stage, then replaces every module of the
package by a .pyd file built from C by Nuitka, only the __init__ files stay Python. build.py feeds
build/stage to PyInstaller, the sources in the repository are never touched.

python compile_core.py --native    only builds native/tbcore.cpp next to the sources, to run
                                   or test the C++ core without a full build

The C++ core (native/tbcore.cpp: export.pdb page layout and waveform bands) becomes
tbcore.dll beside export/cdj/native.py. The Python versions stay as the reference
and the fallback.

Needs: pip install nuitka, and a C compiler (Nuitka offers to fetch MinGW64)."""

from __future__ import annotations

import glob
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent
STAGE = ROOT / "build" / "stage"
PKG = STAGE / "traktor_bridge"

# relative to the package: every module. __init__.py stays Python (a package cannot be a lone
# extension) and __main__.py is the launcher of python -m, the exe starts from main.py
KEEP = ("__init__.py", "__main__.py", "_seal.py")
CORE = ["*.py", "ui/*.py", "sources/*.py", "export/*.py", "export/cdj/*.py"]


def core_files() -> list[Path]:
    files = []
    for pat in CORE:
        files += [p for p in sorted(PKG.glob(pat)) if p.name not in KEEP]
    return files


def write_seal():
    """SHA-256 of every native module of the staged package, packed in the executable as
    _seal.py. It is written after the last compilation: a hash taken earlier would be stale."""
    sys.path.insert(0, str(ROOT))
    from traktor_bridge import integrity
    hashes = integrity.scan(PKG)
    lines = [f"    {rel!r}: {digest!r}," for rel, digest in hashes.items()]
    (PKG / "_seal.py").write_text("# generated by compile_core.py, do not edit\n\nHASHES = {\n" + "\n".join(lines) + "\n}\n",
                                  encoding="utf-8")
    print(f"seal: {len(hashes)} native modules")


def stage():
    shutil.rmtree(STAGE, ignore_errors=True)
    shutil.copytree(ROOT / "traktor_bridge", PKG, ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
    shutil.copyfile(ROOT / "main.py", STAGE / "main.py")


def find_cxx() -> list[str]:
    """A C++ compiler command: TB_CXX, g++, clang++, then the zig that Nuitka downloaded."""
    if os.environ.get("TB_CXX"):
        return [os.environ["TB_CXX"]]
    for name in ("g++", "clang++"):
        if shutil.which(name):
            return [name]
    zigs = []
    for base in {os.environ.get("LOCALAPPDATA", ""), str(Path.home() / "AppData" / "Local")}:
        zigs += glob.glob(os.path.join(base, "Nuitka", "Nuitka", "Cache", "downloads", "pip", "*",
                                       "Lib", "site-packages", "ziglang", "zig.exe"))
    if zigs:
        return [sorted(zigs)[-1], "c++"]
    sys.exit("no C++ compiler: install g++ or clang++, set TB_CXX, or run compile_core.py once "
             "so that Nuitka downloads one")


def build_native(dest: Path):
    """native/tbcore.cpp to a shared library in dest, next to native.py."""
    name = "tbcore.dll" if sys.platform == "win32" else "libtbcore.dylib" if sys.platform == "darwin" else "libtbcore.so"
    out = dest / name
    # a previous failed link leaves the import library behind and the linker then refuses to write
    for old in (out, *dest.glob("tbcore.lib"), *dest.glob("tbcore.pdb")):
        for _ in range(20):               # a Python that loaded the DLL holds it for a moment
            try:
                old.unlink(missing_ok=True)
                break
            except PermissionError:
                time.sleep(0.5)
        else:
            sys.exit(f"{old.name} is in use, close the programs that loaded it")
    # no fused multiply-add: the results must match the Python reference to the last bit
    # -s: no symbols and no .pdb, --gc-sections: only the code that is called stays
    cmd = [*find_cxx(), "-std=c++17", "-O2", "-shared", "-fPIC", "-ffp-contract=off", "-fvisibility=hidden",
           "-fno-rtti", "-ffunction-sections", "-fdata-sections", "-s", "-Wl,--gc-sections",
           "-o", str(out), str(ROOT / "native" / "tbcore.cpp")]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0 or not out.is_file():
        sys.exit("C++ build failed:\n" + r.stderr[-3000:])
    for junk in dest.glob("*.lib"):
        junk.unlink()
    for junk in dest.glob("*.pdb"):
        junk.unlink()
    print(f"native core: {out.relative_to(ROOT) if out.is_relative_to(ROOT) else out} ({out.stat().st_size // 1024} KB)")
    return out


def nuitka_env() -> dict[str, str]:
    """Nuitka 4.2 reads lazy_loader._StubVisitor while scanning librosa, gone from
    lazy_loader 0.6. An older copy in a side folder fixes it without touching the venv."""
    env = dict(os.environ)
    try:
        import lazy_loader
        if hasattr(lazy_loader, "_StubVisitor"):
            return env
    except ImportError:
        return env
    shim = ROOT / "build" / "shim"
    if not shim.exists():
        subprocess.run([sys.executable, "-m", "pip", "install", "lazy_loader==0.5", "--no-deps",
                        "--target", str(shim), "-q"], check=True)
    env["PYTHONPATH"] = str(shim) + os.pathsep + env.get("PYTHONPATH", "")
    return env


def compile_one(src: Path, env: dict[str, str]):
    out = src.parent
    r = subprocess.run(
        [sys.executable, "-m", "nuitka", "--mode=module", str(src), f"--output-dir={out}",
         "--assume-yes-for-downloads", "--remove-output", "--quiet", "--no-pyi-file",
         "--nofollow-imports"],
        capture_output=True, text=True, env=env)
    if r.returncode != 0:
        sys.exit(f"Nuitka failed on {src.relative_to(PKG)}:\n{r.stdout}\n{r.stderr}")
    if not list(out.glob(f"{src.stem}.*.pyd")) and not list(out.glob(f"{src.stem}.*.so")):
        sys.exit(f"no extension produced for {src.relative_to(PKG)}")
    src.unlink()


def main() -> int:
    if "--native" in sys.argv:
        build_native(ROOT / "traktor_bridge" / "export" / "cdj")
        return 0
    try:
        import nuitka  # noqa: F401
    except ImportError:
        sys.exit("Nuitka is missing: pip install nuitka")
    env = nuitka_env()
    stage()
    build_native(PKG / "export" / "cdj")
    files = core_files()
    # one at a time: parallel Nuitka runs share their caches and produced modules that crash on import
    for f in files:
        compile_one(f, env)
    write_seal()
    left = [p.relative_to(PKG) for pat in CORE for p in PKG.glob(pat) if p.suffix == ".py" and p.name not in KEEP]
    print(f"{len(files)} core modules compiled in {STAGE}, {len(left)} core .py left")
    return 0 if not left else 1


if __name__ == "__main__":
    sys.exit(main())
